Repository operate-first/blueprint, pull requests merged in 2020-11, with the labels that each got.

#1 add Architectural Decision Record
  README.md
  docs/adr/0000-use-markdown-architectural-decision-records.md
  docs/adr/0001-use-gpl3-as-license.md
  docs/adr/template.md
Labels: approved, size/L

#2 op1st env
  environments/operate_first.md
  environments/operate_first_environment.png
Labels: size/M

#4 Fix typo on ADR-0000 link in README.md
  README.md
Labels: approved, size/XS

#3 [ADR] Feature selection process
  README.md
  docs/adr/0003-feature-selection-policy.md
Labels: approved, enhancement, size/M

#6 Add ArgoCD Apps of Apps structure ADR
  docs/adr/0004-argocd-apps-of-apps-structure.md
Labels: approved, size/M

#5 introduce management hub ARD
  docs/adr/0003-feature-selection-policy.md
Labels: size/XS
