Repository operate-first/blueprint, pull requests merged in 2021-01, with the labels that each got.

#15 Add ci config files and run linting
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  README.md
  docs/adr/0001-use-gpl3-as-license.md
  docs/adr/0003-feature-selection-policy.md
  docs/adr/0004-argocd-apps-of-apps-structure.md
  docs/adr/0005-support-multi-environments-in-repos.md
  docs/adr/template.md
  environments/operate_first.md
  yamllint-config.yaml
Labels: size/L

#13 Add monitoring ADR
  docs/adr/0006-monitoring-structure.md
Labels: approved, size/M

#17 Add ADR for alerting setup
  docs/adr/0007-alerting-setup.md
Labels: size/M

#20 Add secret management adr
  docs/adr/0008-secrets-management.md
Labels: size/M

#19 feat: Cluster resources ADR
  docs/adr/0009-cluster-resources.md
Labels: size/L

#21 feat: Add ADR for common authentication strategy for applications
  docs/adr/0010-common-auth-for-applications.md
Labels: size/M

#25 Update index in Readme
  README.md
  docs/adr/0005-support-multi-environments-in-repos.md
  docs/adr/0007-alerting-setup.md
  docs/adr/0008-secrets-management.md
  docs/adr/0009-cluster-resources.md
  docs/adr/0010-common-auth-for-applications.md
Labels: size/M
