Repository operate-first/blueprint, pull requests merged in 2021-02, with the labels that each got.

#26 feat: Add operators ADR
  docs/adr/0011-operators.md
Labels: do-not-merge/hold, size/L

#29 Update owners file.
  OWNERS
Labels: size/S

#32 Add ADR 11 to the index.
  README.md
  docs/adr/0011-operators.md
Labels: approved, lgtm, size/XS

#36 Add user story for adding an imagestream
  docs/userstories/add_imagestream_to_jh.md
  docs/userstories/templates/imagestream-template.yaml
Labels: approved, lgtm, size/M

#37 User story: Expand PVC for JupyterHub
  docs/userstories/increase_pvc_size_jh.feature
  docs/userstories/templates/pvc-template.yaml
Labels: approved, size/M

#44 Make .features consistent in formatting.
  docs/userstories/add_imagestream_to_jh.md
  docs/userstories/ops/add_imagestream_to_jh.feature
  docs/userstories/ops/increase_pvc_size_jh.feature
Labels: approved, size/M
