Repository operate-first/blueprint, pull requests merged in 2021-06, with the labels that each got.

#94 feat: ADR for PR reviews
  docs/adr/0016-pr-review.md
Labels: approved, lgtm, size/M

#95 chore: Update ADR list
  README.md
Labels: approved, lgtm, size/XS

#96 remove ipolonsk from owners
  OWNERS
Labels: approved, lgtm, size/XS

#74 Authentication for all platform environments
  README.md
  docs/adr/0017-authentication-for-platform.md
Labels: approved, lgtm, size/M

#98 chore: s/ART/ADR/
  README.md
Labels: approved, lgtm, size/M

#100 Improvements to the blueprints readme
  README.md
Labels: approved, lgtm, size/S
